version: '2'
services:
    ridefixxer-app:
        image: ridefixxer
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ridefixxer-postgresql:5432/rideFixxer
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ridefixxer-postgresql:
        extends:
            file: postgresql.yml
            service: ridefixxer-postgresql
